services:
  nginx:
    build: ./src/nginx
    container_name: dantes-codex-nginx
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - inferno
    restart: unless-stopped

  app:
    build: ./src/app
    container_name: dantes-codex-app
    environment:
      - PHP_HOST=php
      - PHP_PORT=8080
      - FLAG=${FLAG}
    depends_on:
      - php
    networks:
      - inferno
    restart: unless-stopped
    volumes:
      - relics:/relics

  php:
    build: ./src/php
    container_name: dantes-codex-php
    environment:
      - FLAG=${FLAG}
    networks:
      - inferno
    restart: unless-stopped
    volumes:
      - relics:/relics

  bot:
    build: ./src/bot
    container_name: dantes-codex-bot
    environment:
      - FLAG=${FLAG}
      - ENVIRONMENT=production
    ports:
      - "4000:4000"
    networks:
      - inferno
    restart: unless-stopped

volumes:
  relics:

networks:
  inferno:
    driver: bridge
